[package]
name = "rubiks-cube"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9"
bevy-inspector-egui = "0.14.0"
bevy_mod_picking = "0.11.0"
bevy_mod_raycast = "0.7.0"
rand = "0.8.5"