[package]
name = "rubiks-cube"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12"
bevy_mod_picking = "0.17"
bevy_egui = "0.24"
rand = "0.8.5"