[package]
name = "rubiks-cube"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13"
bevy_mod_picking = "0.18"
bevy_egui = "0.25"
rand = "0.8.5"